### ISSUE TITLE
Add support to specify for lower cased keywords

### ISSUE THREAD

**Issue by thomasf** [jfrazelle/dockfmt#1]
I find that whole upper case keyword style both ugly and very unnecessary  since keywords only exists in the first column and are easy to spot either way. What do you think?

**Comment by jfrazelle** [comment]
I like the upper case, I think it looks weird otherwise. It is supposed to be a directive. This tool will be opinionated like gofmt.

**Comment by thomasf** [comment]
alright, if I need this it will be a quite uncomplicated fork to maintain anyways.
